<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Testing</title>
</head>
<body>

<table id="ex" class="table table-striped table-bordered" style="width:70%;">
  <thead>
    <tr>
      <th>head1</th>
      <th>head2</th>
      <th>head3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
    <tr>
      <td>isi01</td>
      <td>isi02</td>
      <td>isi03</td>
    </tr>
    <tr>
      <td>sis1</td>
      <td>sis2</td>
      <td>sis3</td>
    </tr>
    <tr>
      <td>did1</td>
      <td>did2</td>
      <td>did3</td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <th>footer1</th>
      <th>footer2</th>
      <th>footer3</th>
    </tr>
  </tfoot>
</table>

  <script>
  $(document).ready(function(){
    $('#ex').DataTable()
  })
  </script>
</body>
</html>
